FROM tensorflow/tensorflow:2.13.0-gpu-jupyter
RUN pip install "ray[rllib]" poke-env ipython ipykernel ipywidgets tqdm tensorboard
RUN apt-get update && apt-get install -y git
RUN mkdir /app
WORKDIR /app
EXPOSE 8888
EXPOSE 8000
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]